title: Prashant Srivastava
logo: /assets/img/my.jpg
description: I’m a Senior Staff Engineer for Nagarro, a software developer focused on software solutions. In this role, I am a part of the development team to design and develop .Net applications.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
