title: Prashant Srivastava
logo: /assets/img/my.jpg
description: I’m a Senior Staff Engineer for Nagarro, an architect focused on software solutions.
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
